name: digitale_kreidetafel

description: Digitale Kreidetafel

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  shared_preferences: ^2.2.3
  mobile_scanner: ^5.1.1
  image_picker: ^1.1.2

flutter:
  uses-material-design: true

  fonts:
    - family: Gobsmacked
      fonts:
        - asset: assets/fonts/Gobsmacked.otf
